/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from "./../../pages/__root";
import { Route as AuthRouteRouteImport } from "./../../pages/auth/route";
import { Route as InnerRouteRouteImport } from "./../../pages/_inner/route";
import { Route as IndexRouteImport } from "./../../pages/index";
import { Route as AuthIndexRouteImport } from "./../../pages/auth/index";
import { Route as AuthResetPasswordRouteImport } from "./../../pages/auth/reset-password";
import { Route as AuthForgotPasswordRouteImport } from "./../../pages/auth/forgot-password";
import { Route as AuthAuthFormRouteRouteImport } from "./../../pages/auth/_auth-form/route";
import { Route as InnerTeacherRouteRouteImport } from "./../../pages/_inner/teacher/route";
import { Route as InnerStudentRouteRouteImport } from "./../../pages/_inner/student/route";
import { Route as InnerAdminRouteRouteImport } from "./../../pages/_inner/admin/route";
import { Route as InnerTeacherIndexRouteImport } from "./../../pages/_inner/teacher/index";
import { Route as InnerStudentIndexRouteImport } from "./../../pages/_inner/student/index";
import { Route as InnerAdminIndexRouteImport } from "./../../pages/_inner/admin/index";
import { Route as AuthAuthFormRegistrationRouteImport } from "./../../pages/auth/_auth-form/registration";
import { Route as AuthAuthFormLoginRouteImport } from "./../../pages/auth/_auth-form/login";
import { Route as InnerTeacherDashboardRouteImport } from "./../../pages/_inner/teacher/dashboard";
import { Route as InnerTeacherContactsRouteImport } from "./../../pages/_inner/teacher/contacts";
import { Route as InnerStudentDashboardRouteImport } from "./../../pages/_inner/student/dashboard";
import { Route as InnerAdminDashboardRouteImport } from "./../../pages/_inner/admin/dashboard";

const AuthRouteRoute = AuthRouteRouteImport.update({
  id: "/auth",
  path: "/auth",
  getParentRoute: () => rootRouteImport,
} as any);
const InnerRouteRoute = InnerRouteRouteImport.update({
  id: "/_inner",
  getParentRoute: () => rootRouteImport,
} as any);
const IndexRoute = IndexRouteImport.update({
  id: "/",
  path: "/",
  getParentRoute: () => rootRouteImport,
} as any);
const AuthIndexRoute = AuthIndexRouteImport.update({
  id: "/",
  path: "/",
  getParentRoute: () => AuthRouteRoute,
} as any);
const AuthResetPasswordRoute = AuthResetPasswordRouteImport.update({
  id: "/reset-password",
  path: "/reset-password",
  getParentRoute: () => AuthRouteRoute,
} as any);
const AuthForgotPasswordRoute = AuthForgotPasswordRouteImport.update({
  id: "/forgot-password",
  path: "/forgot-password",
  getParentRoute: () => AuthRouteRoute,
} as any);
const AuthAuthFormRouteRoute = AuthAuthFormRouteRouteImport.update({
  id: "/_auth-form",
  getParentRoute: () => AuthRouteRoute,
} as any);
const InnerTeacherRouteRoute = InnerTeacherRouteRouteImport.update({
  id: "/teacher",
  path: "/teacher",
  getParentRoute: () => InnerRouteRoute,
} as any);
const InnerStudentRouteRoute = InnerStudentRouteRouteImport.update({
  id: "/student",
  path: "/student",
  getParentRoute: () => InnerRouteRoute,
} as any);
const InnerAdminRouteRoute = InnerAdminRouteRouteImport.update({
  id: "/admin",
  path: "/admin",
  getParentRoute: () => InnerRouteRoute,
} as any);
const InnerTeacherIndexRoute = InnerTeacherIndexRouteImport.update({
  id: "/",
  path: "/",
  getParentRoute: () => InnerTeacherRouteRoute,
} as any);
const InnerStudentIndexRoute = InnerStudentIndexRouteImport.update({
  id: "/",
  path: "/",
  getParentRoute: () => InnerStudentRouteRoute,
} as any);
const InnerAdminIndexRoute = InnerAdminIndexRouteImport.update({
  id: "/",
  path: "/",
  getParentRoute: () => InnerAdminRouteRoute,
} as any);
const AuthAuthFormRegistrationRoute =
  AuthAuthFormRegistrationRouteImport.update({
    id: "/registration",
    path: "/registration",
    getParentRoute: () => AuthAuthFormRouteRoute,
  } as any);
const AuthAuthFormLoginRoute = AuthAuthFormLoginRouteImport.update({
  id: "/login",
  path: "/login",
  getParentRoute: () => AuthAuthFormRouteRoute,
} as any);
const InnerTeacherDashboardRoute = InnerTeacherDashboardRouteImport.update({
  id: "/dashboard",
  path: "/dashboard",
  getParentRoute: () => InnerTeacherRouteRoute,
} as any);
const InnerTeacherContactsRoute = InnerTeacherContactsRouteImport.update({
  id: "/contacts",
  path: "/contacts",
  getParentRoute: () => InnerTeacherRouteRoute,
} as any);
const InnerStudentDashboardRoute = InnerStudentDashboardRouteImport.update({
  id: "/dashboard",
  path: "/dashboard",
  getParentRoute: () => InnerStudentRouteRoute,
} as any);
const InnerAdminDashboardRoute = InnerAdminDashboardRouteImport.update({
  id: "/dashboard",
  path: "/dashboard",
  getParentRoute: () => InnerAdminRouteRoute,
} as any);

export interface FileRoutesByFullPath {
  "/": typeof IndexRoute;
  "/auth": typeof AuthAuthFormRouteRouteWithChildren;
  "/admin": typeof InnerAdminRouteRouteWithChildren;
  "/student": typeof InnerStudentRouteRouteWithChildren;
  "/teacher": typeof InnerTeacherRouteRouteWithChildren;
  "/auth/forgot-password": typeof AuthForgotPasswordRoute;
  "/auth/reset-password": typeof AuthResetPasswordRoute;
  "/auth/": typeof AuthIndexRoute;
  "/admin/dashboard": typeof InnerAdminDashboardRoute;
  "/student/dashboard": typeof InnerStudentDashboardRoute;
  "/teacher/contacts": typeof InnerTeacherContactsRoute;
  "/teacher/dashboard": typeof InnerTeacherDashboardRoute;
  "/auth/login": typeof AuthAuthFormLoginRoute;
  "/auth/registration": typeof AuthAuthFormRegistrationRoute;
  "/admin/": typeof InnerAdminIndexRoute;
  "/student/": typeof InnerStudentIndexRoute;
  "/teacher/": typeof InnerTeacherIndexRoute;
}
export interface FileRoutesByTo {
  "/": typeof IndexRoute;
  "/auth": typeof AuthIndexRoute;
  "/auth/forgot-password": typeof AuthForgotPasswordRoute;
  "/auth/reset-password": typeof AuthResetPasswordRoute;
  "/admin/dashboard": typeof InnerAdminDashboardRoute;
  "/student/dashboard": typeof InnerStudentDashboardRoute;
  "/teacher/contacts": typeof InnerTeacherContactsRoute;
  "/teacher/dashboard": typeof InnerTeacherDashboardRoute;
  "/auth/login": typeof AuthAuthFormLoginRoute;
  "/auth/registration": typeof AuthAuthFormRegistrationRoute;
  "/admin": typeof InnerAdminIndexRoute;
  "/student": typeof InnerStudentIndexRoute;
  "/teacher": typeof InnerTeacherIndexRoute;
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport;
  "/": typeof IndexRoute;
  "/_inner": typeof InnerRouteRouteWithChildren;
  "/auth": typeof AuthRouteRouteWithChildren;
  "/_inner/admin": typeof InnerAdminRouteRouteWithChildren;
  "/_inner/student": typeof InnerStudentRouteRouteWithChildren;
  "/_inner/teacher": typeof InnerTeacherRouteRouteWithChildren;
  "/auth/_auth-form": typeof AuthAuthFormRouteRouteWithChildren;
  "/auth/forgot-password": typeof AuthForgotPasswordRoute;
  "/auth/reset-password": typeof AuthResetPasswordRoute;
  "/auth/": typeof AuthIndexRoute;
  "/_inner/admin/dashboard": typeof InnerAdminDashboardRoute;
  "/_inner/student/dashboard": typeof InnerStudentDashboardRoute;
  "/_inner/teacher/contacts": typeof InnerTeacherContactsRoute;
  "/_inner/teacher/dashboard": typeof InnerTeacherDashboardRoute;
  "/auth/_auth-form/login": typeof AuthAuthFormLoginRoute;
  "/auth/_auth-form/registration": typeof AuthAuthFormRegistrationRoute;
  "/_inner/admin/": typeof InnerAdminIndexRoute;
  "/_inner/student/": typeof InnerStudentIndexRoute;
  "/_inner/teacher/": typeof InnerTeacherIndexRoute;
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath;
  fullPaths:
    | "/"
    | "/auth"
    | "/admin"
    | "/student"
    | "/teacher"
    | "/auth/forgot-password"
    | "/auth/reset-password"
    | "/auth/"
    | "/admin/dashboard"
    | "/student/dashboard"
    | "/teacher/contacts"
    | "/teacher/dashboard"
    | "/auth/login"
    | "/auth/registration"
    | "/admin/"
    | "/student/"
    | "/teacher/";
  fileRoutesByTo: FileRoutesByTo;
  to:
    | "/"
    | "/auth"
    | "/auth/forgot-password"
    | "/auth/reset-password"
    | "/admin/dashboard"
    | "/student/dashboard"
    | "/teacher/contacts"
    | "/teacher/dashboard"
    | "/auth/login"
    | "/auth/registration"
    | "/admin"
    | "/student"
    | "/teacher";
  id:
    | "__root__"
    | "/"
    | "/_inner"
    | "/auth"
    | "/_inner/admin"
    | "/_inner/student"
    | "/_inner/teacher"
    | "/auth/_auth-form"
    | "/auth/forgot-password"
    | "/auth/reset-password"
    | "/auth/"
    | "/_inner/admin/dashboard"
    | "/_inner/student/dashboard"
    | "/_inner/teacher/contacts"
    | "/_inner/teacher/dashboard"
    | "/auth/_auth-form/login"
    | "/auth/_auth-form/registration"
    | "/_inner/admin/"
    | "/_inner/student/"
    | "/_inner/teacher/";
  fileRoutesById: FileRoutesById;
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute;
  InnerRouteRoute: typeof InnerRouteRouteWithChildren;
  AuthRouteRoute: typeof AuthRouteRouteWithChildren;
}

declare module "@tanstack/react-router" {
  interface FileRoutesByPath {
    "/auth": {
      id: "/auth";
      path: "/auth";
      fullPath: "/auth";
      preLoaderRoute: typeof AuthRouteRouteImport;
      parentRoute: typeof rootRouteImport;
    };
    "/_inner": {
      id: "/_inner";
      path: "";
      fullPath: "/";
      preLoaderRoute: typeof InnerRouteRouteImport;
      parentRoute: typeof rootRouteImport;
    };
    "/": {
      id: "/";
      path: "/";
      fullPath: "/";
      preLoaderRoute: typeof IndexRouteImport;
      parentRoute: typeof rootRouteImport;
    };
    "/auth/": {
      id: "/auth/";
      path: "/";
      fullPath: "/auth/";
      preLoaderRoute: typeof AuthIndexRouteImport;
      parentRoute: typeof AuthRouteRoute;
    };
    "/auth/reset-password": {
      id: "/auth/reset-password";
      path: "/reset-password";
      fullPath: "/auth/reset-password";
      preLoaderRoute: typeof AuthResetPasswordRouteImport;
      parentRoute: typeof AuthRouteRoute;
    };
    "/auth/forgot-password": {
      id: "/auth/forgot-password";
      path: "/forgot-password";
      fullPath: "/auth/forgot-password";
      preLoaderRoute: typeof AuthForgotPasswordRouteImport;
      parentRoute: typeof AuthRouteRoute;
    };
    "/auth/_auth-form": {
      id: "/auth/_auth-form";
      path: "";
      fullPath: "/auth";
      preLoaderRoute: typeof AuthAuthFormRouteRouteImport;
      parentRoute: typeof AuthRouteRoute;
    };
    "/_inner/teacher": {
      id: "/_inner/teacher";
      path: "/teacher";
      fullPath: "/teacher";
      preLoaderRoute: typeof InnerTeacherRouteRouteImport;
      parentRoute: typeof InnerRouteRoute;
    };
    "/_inner/student": {
      id: "/_inner/student";
      path: "/student";
      fullPath: "/student";
      preLoaderRoute: typeof InnerStudentRouteRouteImport;
      parentRoute: typeof InnerRouteRoute;
    };
    "/_inner/admin": {
      id: "/_inner/admin";
      path: "/admin";
      fullPath: "/admin";
      preLoaderRoute: typeof InnerAdminRouteRouteImport;
      parentRoute: typeof InnerRouteRoute;
    };
    "/_inner/teacher/": {
      id: "/_inner/teacher/";
      path: "/";
      fullPath: "/teacher/";
      preLoaderRoute: typeof InnerTeacherIndexRouteImport;
      parentRoute: typeof InnerTeacherRouteRoute;
    };
    "/_inner/student/": {
      id: "/_inner/student/";
      path: "/";
      fullPath: "/student/";
      preLoaderRoute: typeof InnerStudentIndexRouteImport;
      parentRoute: typeof InnerStudentRouteRoute;
    };
    "/_inner/admin/": {
      id: "/_inner/admin/";
      path: "/";
      fullPath: "/admin/";
      preLoaderRoute: typeof InnerAdminIndexRouteImport;
      parentRoute: typeof InnerAdminRouteRoute;
    };
    "/auth/_auth-form/registration": {
      id: "/auth/_auth-form/registration";
      path: "/registration";
      fullPath: "/auth/registration";
      preLoaderRoute: typeof AuthAuthFormRegistrationRouteImport;
      parentRoute: typeof AuthAuthFormRouteRoute;
    };
    "/auth/_auth-form/login": {
      id: "/auth/_auth-form/login";
      path: "/login";
      fullPath: "/auth/login";
      preLoaderRoute: typeof AuthAuthFormLoginRouteImport;
      parentRoute: typeof AuthAuthFormRouteRoute;
    };
    "/_inner/teacher/dashboard": {
      id: "/_inner/teacher/dashboard";
      path: "/dashboard";
      fullPath: "/teacher/dashboard";
      preLoaderRoute: typeof InnerTeacherDashboardRouteImport;
      parentRoute: typeof InnerTeacherRouteRoute;
    };
    "/_inner/teacher/contacts": {
      id: "/_inner/teacher/contacts";
      path: "/contacts";
      fullPath: "/teacher/contacts";
      preLoaderRoute: typeof InnerTeacherContactsRouteImport;
      parentRoute: typeof InnerTeacherRouteRoute;
    };
    "/_inner/student/dashboard": {
      id: "/_inner/student/dashboard";
      path: "/dashboard";
      fullPath: "/student/dashboard";
      preLoaderRoute: typeof InnerStudentDashboardRouteImport;
      parentRoute: typeof InnerStudentRouteRoute;
    };
    "/_inner/admin/dashboard": {
      id: "/_inner/admin/dashboard";
      path: "/dashboard";
      fullPath: "/admin/dashboard";
      preLoaderRoute: typeof InnerAdminDashboardRouteImport;
      parentRoute: typeof InnerAdminRouteRoute;
    };
  }
}

interface InnerAdminRouteRouteChildren {
  InnerAdminDashboardRoute: typeof InnerAdminDashboardRoute;
  InnerAdminIndexRoute: typeof InnerAdminIndexRoute;
}

const InnerAdminRouteRouteChildren: InnerAdminRouteRouteChildren = {
  InnerAdminDashboardRoute: InnerAdminDashboardRoute,
  InnerAdminIndexRoute: InnerAdminIndexRoute,
};

const InnerAdminRouteRouteWithChildren = InnerAdminRouteRoute._addFileChildren(
  InnerAdminRouteRouteChildren,
);

interface InnerStudentRouteRouteChildren {
  InnerStudentDashboardRoute: typeof InnerStudentDashboardRoute;
  InnerStudentIndexRoute: typeof InnerStudentIndexRoute;
}

const InnerStudentRouteRouteChildren: InnerStudentRouteRouteChildren = {
  InnerStudentDashboardRoute: InnerStudentDashboardRoute,
  InnerStudentIndexRoute: InnerStudentIndexRoute,
};

const InnerStudentRouteRouteWithChildren =
  InnerStudentRouteRoute._addFileChildren(InnerStudentRouteRouteChildren);

interface InnerTeacherRouteRouteChildren {
  InnerTeacherContactsRoute: typeof InnerTeacherContactsRoute;
  InnerTeacherDashboardRoute: typeof InnerTeacherDashboardRoute;
  InnerTeacherIndexRoute: typeof InnerTeacherIndexRoute;
}

const InnerTeacherRouteRouteChildren: InnerTeacherRouteRouteChildren = {
  InnerTeacherContactsRoute: InnerTeacherContactsRoute,
  InnerTeacherDashboardRoute: InnerTeacherDashboardRoute,
  InnerTeacherIndexRoute: InnerTeacherIndexRoute,
};

const InnerTeacherRouteRouteWithChildren =
  InnerTeacherRouteRoute._addFileChildren(InnerTeacherRouteRouteChildren);

interface InnerRouteRouteChildren {
  InnerAdminRouteRoute: typeof InnerAdminRouteRouteWithChildren;
  InnerStudentRouteRoute: typeof InnerStudentRouteRouteWithChildren;
  InnerTeacherRouteRoute: typeof InnerTeacherRouteRouteWithChildren;
}

const InnerRouteRouteChildren: InnerRouteRouteChildren = {
  InnerAdminRouteRoute: InnerAdminRouteRouteWithChildren,
  InnerStudentRouteRoute: InnerStudentRouteRouteWithChildren,
  InnerTeacherRouteRoute: InnerTeacherRouteRouteWithChildren,
};

const InnerRouteRouteWithChildren = InnerRouteRoute._addFileChildren(
  InnerRouteRouteChildren,
);

interface AuthAuthFormRouteRouteChildren {
  AuthAuthFormLoginRoute: typeof AuthAuthFormLoginRoute;
  AuthAuthFormRegistrationRoute: typeof AuthAuthFormRegistrationRoute;
}

const AuthAuthFormRouteRouteChildren: AuthAuthFormRouteRouteChildren = {
  AuthAuthFormLoginRoute: AuthAuthFormLoginRoute,
  AuthAuthFormRegistrationRoute: AuthAuthFormRegistrationRoute,
};

const AuthAuthFormRouteRouteWithChildren =
  AuthAuthFormRouteRoute._addFileChildren(AuthAuthFormRouteRouteChildren);

interface AuthRouteRouteChildren {
  AuthAuthFormRouteRoute: typeof AuthAuthFormRouteRouteWithChildren;
  AuthForgotPasswordRoute: typeof AuthForgotPasswordRoute;
  AuthResetPasswordRoute: typeof AuthResetPasswordRoute;
  AuthIndexRoute: typeof AuthIndexRoute;
}

const AuthRouteRouteChildren: AuthRouteRouteChildren = {
  AuthAuthFormRouteRoute: AuthAuthFormRouteRouteWithChildren,
  AuthForgotPasswordRoute: AuthForgotPasswordRoute,
  AuthResetPasswordRoute: AuthResetPasswordRoute,
  AuthIndexRoute: AuthIndexRoute,
};

const AuthRouteRouteWithChildren = AuthRouteRoute._addFileChildren(
  AuthRouteRouteChildren,
);

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  InnerRouteRoute: InnerRouteRouteWithChildren,
  AuthRouteRoute: AuthRouteRouteWithChildren,
};
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>();
