/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

// Import Routes

import { Route as rootRoute } from "./../pages/__root";
import { Route as AuthRouteImport } from "./../pages/auth/route";
import { Route as IndexImport } from "./../pages/index";
import { Route as AuthIndexImport } from "./../pages/auth/index";
import { Route as AuthForgotPasswordImport } from "./../pages/auth/forgot-password";
import { Route as AuthAuthFormRouteImport } from "./../pages/auth/_auth-form/route";
import { Route as AuthAuthFormRegistrationImport } from "./../pages/auth/_auth-form/registration";
import { Route as AuthAuthFormLoginImport } from "./../pages/auth/_auth-form/login";

// Create/Update Routes

const AuthRouteRoute = AuthRouteImport.update({
  id: "/auth",
  path: "/auth",
  getParentRoute: () => rootRoute,
} as any);

const IndexRoute = IndexImport.update({
  id: "/",
  path: "/",
  getParentRoute: () => rootRoute,
} as any);

const AuthIndexRoute = AuthIndexImport.update({
  id: "/",
  path: "/",
  getParentRoute: () => AuthRouteRoute,
} as any);

const AuthForgotPasswordRoute = AuthForgotPasswordImport.update({
  id: "/forgot-password",
  path: "/forgot-password",
  getParentRoute: () => AuthRouteRoute,
} as any);

const AuthAuthFormRouteRoute = AuthAuthFormRouteImport.update({
  id: "/_auth-form",
  getParentRoute: () => AuthRouteRoute,
} as any);

const AuthAuthFormRegistrationRoute = AuthAuthFormRegistrationImport.update({
  id: "/registration",
  path: "/registration",
  getParentRoute: () => AuthAuthFormRouteRoute,
} as any);

const AuthAuthFormLoginRoute = AuthAuthFormLoginImport.update({
  id: "/login",
  path: "/login",
  getParentRoute: () => AuthAuthFormRouteRoute,
} as any);

// Populate the FileRoutesByPath interface

declare module "@tanstack/react-router" {
  interface FileRoutesByPath {
    "/": {
      id: "/";
      path: "/";
      fullPath: "/";
      preLoaderRoute: typeof IndexImport;
      parentRoute: typeof rootRoute;
    };
    "/auth": {
      id: "/auth";
      path: "/auth";
      fullPath: "/auth";
      preLoaderRoute: typeof AuthRouteImport;
      parentRoute: typeof rootRoute;
    };
    "/auth/_auth-form": {
      id: "/auth/_auth-form";
      path: "";
      fullPath: "/auth";
      preLoaderRoute: typeof AuthAuthFormRouteImport;
      parentRoute: typeof AuthRouteImport;
    };
    "/auth/forgot-password": {
      id: "/auth/forgot-password";
      path: "/forgot-password";
      fullPath: "/auth/forgot-password";
      preLoaderRoute: typeof AuthForgotPasswordImport;
      parentRoute: typeof AuthRouteImport;
    };
    "/auth/": {
      id: "/auth/";
      path: "/";
      fullPath: "/auth/";
      preLoaderRoute: typeof AuthIndexImport;
      parentRoute: typeof AuthRouteImport;
    };
    "/auth/_auth-form/login": {
      id: "/auth/_auth-form/login";
      path: "/login";
      fullPath: "/auth/login";
      preLoaderRoute: typeof AuthAuthFormLoginImport;
      parentRoute: typeof AuthAuthFormRouteImport;
    };
    "/auth/_auth-form/registration": {
      id: "/auth/_auth-form/registration";
      path: "/registration";
      fullPath: "/auth/registration";
      preLoaderRoute: typeof AuthAuthFormRegistrationImport;
      parentRoute: typeof AuthAuthFormRouteImport;
    };
  }
}

// Create and export the route tree

interface AuthAuthFormRouteRouteChildren {
  AuthAuthFormLoginRoute: typeof AuthAuthFormLoginRoute;
  AuthAuthFormRegistrationRoute: typeof AuthAuthFormRegistrationRoute;
}

const AuthAuthFormRouteRouteChildren: AuthAuthFormRouteRouteChildren = {
  AuthAuthFormLoginRoute: AuthAuthFormLoginRoute,
  AuthAuthFormRegistrationRoute: AuthAuthFormRegistrationRoute,
};

const AuthAuthFormRouteRouteWithChildren =
  AuthAuthFormRouteRoute._addFileChildren(AuthAuthFormRouteRouteChildren);

interface AuthRouteRouteChildren {
  AuthAuthFormRouteRoute: typeof AuthAuthFormRouteRouteWithChildren;
  AuthForgotPasswordRoute: typeof AuthForgotPasswordRoute;
  AuthIndexRoute: typeof AuthIndexRoute;
}

const AuthRouteRouteChildren: AuthRouteRouteChildren = {
  AuthAuthFormRouteRoute: AuthAuthFormRouteRouteWithChildren,
  AuthForgotPasswordRoute: AuthForgotPasswordRoute,
  AuthIndexRoute: AuthIndexRoute,
};

const AuthRouteRouteWithChildren = AuthRouteRoute._addFileChildren(
  AuthRouteRouteChildren,
);

export interface FileRoutesByFullPath {
  "/": typeof IndexRoute;
  "/auth": typeof AuthAuthFormRouteRouteWithChildren;
  "/auth/forgot-password": typeof AuthForgotPasswordRoute;
  "/auth/": typeof AuthIndexRoute;
  "/auth/login": typeof AuthAuthFormLoginRoute;
  "/auth/registration": typeof AuthAuthFormRegistrationRoute;
}

export interface FileRoutesByTo {
  "/": typeof IndexRoute;
  "/auth": typeof AuthIndexRoute;
  "/auth/forgot-password": typeof AuthForgotPasswordRoute;
  "/auth/login": typeof AuthAuthFormLoginRoute;
  "/auth/registration": typeof AuthAuthFormRegistrationRoute;
}

export interface FileRoutesById {
  __root__: typeof rootRoute;
  "/": typeof IndexRoute;
  "/auth": typeof AuthRouteRouteWithChildren;
  "/auth/_auth-form": typeof AuthAuthFormRouteRouteWithChildren;
  "/auth/forgot-password": typeof AuthForgotPasswordRoute;
  "/auth/": typeof AuthIndexRoute;
  "/auth/_auth-form/login": typeof AuthAuthFormLoginRoute;
  "/auth/_auth-form/registration": typeof AuthAuthFormRegistrationRoute;
}

export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath;
  fullPaths:
    | "/"
    | "/auth"
    | "/auth/forgot-password"
    | "/auth/"
    | "/auth/login"
    | "/auth/registration";
  fileRoutesByTo: FileRoutesByTo;
  to:
    | "/"
    | "/auth"
    | "/auth/forgot-password"
    | "/auth/login"
    | "/auth/registration";
  id:
    | "__root__"
    | "/"
    | "/auth"
    | "/auth/_auth-form"
    | "/auth/forgot-password"
    | "/auth/"
    | "/auth/_auth-form/login"
    | "/auth/_auth-form/registration";
  fileRoutesById: FileRoutesById;
}

export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute;
  AuthRouteRoute: typeof AuthRouteRouteWithChildren;
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AuthRouteRoute: AuthRouteRouteWithChildren,
};

export const routeTree = rootRoute
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>();

/* ROUTE_MANIFEST_START
{
  "routes": {
    "__root__": {
      "filePath": "__root.tsx",
      "children": [
        "/",
        "/auth"
      ]
    },
    "/": {
      "filePath": "index.tsx"
    },
    "/auth": {
      "filePath": "auth/route.tsx",
      "children": [
        "/auth/_auth-form",
        "/auth/forgot-password",
        "/auth/"
      ]
    },
    "/auth/_auth-form": {
      "filePath": "auth/_auth-form/route.tsx",
      "parent": "/auth",
      "children": [
        "/auth/_auth-form/login",
        "/auth/_auth-form/registration"
      ]
    },
    "/auth/forgot-password": {
      "filePath": "auth/forgot-password.tsx",
      "parent": "/auth"
    },
    "/auth/": {
      "filePath": "auth/index.tsx",
      "parent": "/auth"
    },
    "/auth/_auth-form/login": {
      "filePath": "auth/_auth-form/login.tsx",
      "parent": "/auth/_auth-form"
    },
    "/auth/_auth-form/registration": {
      "filePath": "auth/_auth-form/registration.tsx",
      "parent": "/auth/_auth-form"
    }
  }
}
ROUTE_MANIFEST_END */
